[tools]
flutter = "3.38.5"
java = "21"
ruby = "3.4.8"

[hooks]
postinstall = [
    "echo ðŸ”§ Running post-install hooks...",
    "dart pub global activate melos && âœ… Melos activated successfully!"
]
